# SPDX-License-Identifier: CC0-1.0
# Target mkinitcpio — match the installed (unpacked) system; kernel is linux-lts.
---
useSystemdHook: true
hooks:
  prepend: []
  append: []
  remove: []
source: "/etc/mkinitcpio.conf"
