---
# Arvora OS Locale Configuration Module
# This file configures locale settings

# Locale configuration file
localeGenPath: "/etc/locale.gen"

# Locale configuration
localeConfPath: "/etc/locale.conf"

# Locale settings
localeSettingsPath: "/etc/default/locale"

# Write locale configuration
writeLocaleConf: true

# Write locale settings
writeLocaleSettings: true
