---
# Arvora OS Machine ID Module Configuration
# This file configures machine ID generation

# Systemd machine ID
systemd: true

# DBUS machine ID
dbus: true

# Symlink to /etc/machine-id
symlink: true
