---
# Arvora OS Network Configuration Module
# This file configures network settings

# Network configuration
configFile: "/etc/systemd/network/20-wired.network"

# Network manager
networkManager: "systemd-networkd"

# Network configuration
networkConfiguration:
  - interface: "*"
    dhcp: true
    dns:
      - "8.8.8.8"
      - "8.8.4.4"
      - "1.1.1.1"
      - "1.0.0.1"
