---
# Arvora OS Umount Module Configuration
# This file configures unmounting of target system

# Unmount target
unmount: true

# Unmount options
unmountOptions:
  - "lazy"
  - "force"

# Unmount timeout
unmountTimeout: 30
